try{
    console.log(z)
}catch(err){
    console.log(err)
}finally{
    console.log('hahahhahhah')
}
    console.log('Oops there is an error')